set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-left ""
set -g status-right '#[fg=#{$thm_crust},bg=#{@thm_teal}] session: #S '
set -g status-right-length 100

set -g mouse off

unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

bind r source-file ~/.config/tmux/tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
